company/urls.py
from django.urls import path
from .views import company, sign_up, contact, home, album

app_name = 'company'

urlpatterns = [ 
    path('about/', company, name='about'),
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('accounts/signup/', sign_up, name='signup'),
    path('album/', album, name='album'),
    ]

menu/urls.py
from django.urls import path
from .views import items

app_name = 'menu'

urlpatterns = [
    path('menu/', items,  name='menu_page'),
    # path('albom/', albom,  name='albom'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include # add this
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls', namespace="company")), # add this
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('menu.urls', namespace="menu")), # add this
    path('api-auth/', include('rest_framework.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Company(models.Model):
    name = models.CharField(_("Name"), max_length=200)
    sub_title = models.CharField(_("Sub titl"), max_length=200)
    description = models.TextField(_("Description"),)
    description_ar = models.TextField(_("Description"),)
    address = models.TextField(_("Address") ,max_length=1000)
    phone = models.CharField(_("Phone"), max_length=200)
    email = models.EmailField(_("Email"), max_length=200)
    logo = models.ImageField(_("Logo"), upload_to='company_logo/', null=True, blank=True)
    location = models.URLField(_("location"), blank=True, null=True)
    fb_link = models.URLField(_("facebook link"), blank=True, null=True)
    ins_link = models.URLField(_("instagram link"), blank=True, null=True)
    tw_link = models.URLField(_("tweeter link"), blank=True, null=True)
 
    def __str__(self):
        return self.name
    
class Users(models.Model):
    user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    phone = models.CharField(_("Phone"), max_length=200)
    city = models.CharField(max_length=20)


    def __str__(self):
        return str(self.user)



class Photo(models.Model):
    image = models.ImageField(_("Image"), upload_to='album/')

    def __str__(self):
        return str(self.pk)


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Users.objects.create(user=instance)

menu/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.


class Menu(models.Model):
    name_ar = models.CharField(_("Arabic Name"), max_length=100)
    name_en = models.CharField(_("English Name"), max_length=100)
    Category = models.ForeignKey('Category', on_delete=models.SET_NULL, related_name='categoryItem', null=True, blank=True)
    SR = models.CharField(_("SR"), max_length=20)
    CAL = models.CharField(_("CAL"), max_length=20, null=True, blank=True)
    def __str__(self):  
        return self.name_en
    

 
    
class Category(models.Model):
    name_ar = models.CharField(_("Arabic Name"), max_length=100)
    name_en = models.CharField(_("English Name"), max_length=100)

    
    def __str__(self):  
        return self.name_en
    


    

company/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

company/views.py
from django.shortcuts import render
from .models import *
from .forms import SignupForm
from django.shortcuts import redirect
# Create your views here.

def company(request):
    company = Company.objects.last()

    context = {
        'company':company,
    }
    return render(request, 'information/about.html', context)

def contact(request):
    company = Company.objects.last()

    context = {
        'company':company,
    }
    return render(request, 'information/contact.html', context)

def home(request):
    company = Company.objects.last()

    context = {
        'company':company,
    }
    return render(request, 'information/home.html', context)


    
def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            phone = request.POST.get('phonenumber')
            city = request.POST.get('city')

            myform = form.save()
            users = Users.objects.get(user__username=username)  
            users.phone = phone
            users.city = city
            users.save()
            

            # # send email
            # send_mail(
            #     subject= 'Greeny Activate Your Account',
            #     message=f"user this code {profile.code} to activate your acount", 
            #     from_email='mahmoudtino56@gmail.com', 
            #     recipient_list= [email],
            #     fail_silently=False
            # )
            return redirect(f"/accounts/login/")

    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {"form":form} )



def album(request):
    photo_list = Photo.objects.all()
    return render(request, 'information/album.html', {'photo_list': photo_list})

menu/views.py
from django.shortcuts import render
from .models import Menu, Category
# Create your views here.

def items(request):
    items = Menu.objects.all()
    Categories = Category.objects.all()

    
    return render(request, 'menu/menu.html', {'items': items, 'Categories': Categories})

company/templates/information/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>About us</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/carousel/">
      <!-- Bootstrap css1 -->


    <!-- Bootstrap core CSS -->
    <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

      <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      body{
      background-color: rgba(153,155,138,0.3);
       }
      .card {
      width: 290px;
      height: 354px;
      border-radius: 20px;
      padding: 5px;
      box-shadow: rgba(114,77,81, 0.2) 0 15px 30px -5px;
      background-image: linear-gradient(144deg,#eb8b69, #724d51 50%);
    }

    .card__content {
      background: #000;
      border-radius: 17px;
      width: 100%;
      height: 100%;
    }
    .card__title{
        text-align: center;
        padding: 3px;
        color: #fff;
    }
    .card__p{
        text-align: center;
        padding: 3px;
        color: #fff;
    }
    .card__icon{
    margin-left: 30%;
    width: 104px;
    height: 104px;
    padding: 5px
    }
    .card__img{
    width: 90%;
    height: 90%;
    border-top-right-radius: 20%;
    }
    .card__2 {
      width: 17em;
      height: 22.5em;
      background: #999b8a;
      transition: 1s ease-in-out;
      clip-path: polygon(30px 0%, 100% 0, 100% calc(100% - 30px), calc(100% - 30px) 100%, 0 100%, 0% 30px);
      border-top-right-radius: 20px;
      border-bottom-left-radius: 20px;
      display: flex;
      flex-direction: column;
      margin-left:30%
    }
    .card__2 span {
      font-weight: bold;
      color: white;
      text-align: center;
      display: block;
      font-size: 16px;
    }
    .card__2 .info {
      font-weight: 400;
      color: white;
      display: block;
      text-align: center;
      font-size: 14px;
      margin: 1em;
    }
    .p-d{
      font-weight: 600;
      color: #686868;
      text-align:justify ;
      font-size: 16px;
      margin: 1em;
      line-height: 32px;
    }
    </style>


    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>

    <main>
      <div class="container marketing">
        <!-- start about section -->
        <section>
          <div class="row featurette mt-5">
              <div class="col-md-7 mt-5">
                <h2 class="featurette-heading" style="color: #724d51">You Need to Hear it From Us?
                    <br>
                    <span style="color:rgba(153,155,138,1)"> Ok..</span>
                </h2>
                <p class="p-d">
                    We are a Saudi Brand inspired by the heritage and lifestyle of the Japanese Culture, we provide an entertainment and social space to our clients,
                    with the highest quality drinks and treats, and continuous surprises on the shelves! joy is our native language,
                    and culture is the medium in which we communicate and deliver our ideas through. We are minimalists,
                    we help our clients in feeling less stressful and more joyful, we are also detail-oriented, we never miss a detail, but don’t worry,
                    it doesn’t mean that we’ll stalk you, but we’ll be able to recognize your laugh, distinguish your smile, and feel the joy in your heart if you walked through our doors,
                    we are consistent in what we deliver to our clients, as consistency is a way to build a long-term connection with our communities, and communities are the essence of our work,
                    they are why we are here from the first place!
                </p>
              </div>
              <div class="col-md-5">
                <img class="card__img mt-5" src="{% static 'images/03.png' %}" alt="icon" />
              </div>
          </div>
        </section>
          <!-- end about section -->
          <!-- start values section -->
          <section class="mt-5">
            <h1 class="text-center" style="color: #724d51">
                What Values Influences Us ?
            </h1>
            <div class="row mb-5 mt-3">
              <div class="col-md-3">
                  <div class="card">
                    <div class="card__content">
                         <img class="card__icon mt-5" src="{% static 'images/sustainability.png' %}" alt="icon" />
                        <h4 class="card__title">Sustainability</h4>
                        <p class="card__p">
                            We choose environment-friendly
                            products, and we sustain a long-term
                            relationships with our customers.
                        </p>
                    </div>
                  </div>
              </div>
                <div class="col-md-3">
                  <div class="card">
                    <div class="card__content">
                         <img class="card__icon mt-5" src="{% static 'images/culture.png' %}" alt="icon" />
                        <h4 class="card__title">Culture</h4>
                        <p class="card__p">
                            We offer a multi-cultural experience that can change the way people
                            perceive life and view the world around them.
                        </p>
                    </div>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="card">
                    <div class="card__content">
                         <img class="card__icon mt-5" src="{% static 'images/Connection.png' %}" alt="icon" />
                        <h4 class="card__title">Connection</h4>
                        <p class="card__p">
                            We make people connect with themselves and their surroundings by
                            connecting with others. We call it the bonding experiment.
                        </p>
                    </div>
                  </div>
              </div>
                <div class="col-md-3">
                  <div class="card">
                    <div class="card__content">
                         <img class="card__icon mt-5" src="{% static 'images/Value.png' %}" alt="icon" />
                        <h4 class="card__title">Value Added</h4>
                        <p class="card__p">
                            We care about the messages being communicated and values
                            being delivered within our services and our through our products
                            for all involved parties.
                        </p>
                    </div>
                  </div>
                </div>
            </div>
          </section>
          <!-- end values section -->
          <!-- start about2 section -->
          <section class="mt-5">
              <div class="row featurette mt-5">
                  <div class="col-md-7 order-md-2 mt-5">
                    <h2 class="featurette-heading" style="color: #724d51">What Do We Exactly Provide in Janken?</h2>
                    <p class="p-d">In simple words, we provide you an entertainment and
                        social space where you can disconnect from the digital world and connect to the real world through playing and engaging with your
                        surroundings, and we provide you with a unique selections of food and beverages that can make you engage in the moment with your five senses.
                        Disconnecting from the virtual lives and engaging in a real social experiment can make a difference, and the secret is in the “endorphins hormones “, which is “our favorite hormone”! It releases all the stress and activates parts in the brain where you can feel your creative self again, and become more joyful,
                        if you really engaged in the moment.</p>
                  </div>
                  <div class="col-md-5 order-md-1">
                    <img class="card__img mt-5" src="{% static 'images/10.png' %}" alt="icon" />
                  </div>
                </div>
          </section>
          <!-- end about2 section -->
          <!-- start about3 section -->
          <section class="mt-5">
            <div class="row featurette mt-5">
              <div class="col-md-7">
                    <h2 class="featurette-heading" style="color: #724d51">What Do We Work on Everyday? </h2>
                    <p class="p-d">
                        We are dreamers, creators, and innovators. We want to leave an impact on the society and make a change, it might sound cliche, but it is real.
                        Our spaces can be utilized in various of ways, and our shelves are always waiting for something new, we welcome you inside Janken at all times,
                        and we come to you with all the passion we have within us, to fill your clients with it too.
                        And we can’t define ourselves just yet.. as we are shaping ourselves as the days go by. We believe that our journey will take us where we want to go,
                        so how about you share this journey with us?
                    </p>
              </div>
              <div class="col-md-5">
                  <img class="card__img mt-5" src="{% static 'images/01.png' %}" alt="icon" />
            </div>
        </div>
          </section>
          <!-- end about3 section -->
          <!-- start about4 section -->
          <section class="mt-5">
              <h2 class="featurette-heading text-center" style="color: #724d51">What Are Our Two Main Lines of Service?</h2>
              <div class="row mt-5 mb-5">
                  <div class="col-sm-6">
                       <div class="card__2">
                            <div>
                                <img class="card__icon mt-5" src="{% static 'images/board-game.png' %}" alt="icon" />
                            </div>
                             <span>Entertainment — The Joy Line</span>
                              <p class="info">
                                  Let’s start with definitions, to entertain is to make people feel a certain amount of emotions.
                                  In our shelves, there are variety of board games, card games,
                                  and kinetic games that will make you feel yourself once again.
                              </p>
                      </div>
                  </div>
                  <div class="col-sm-6">
                       <div class="card__2">
                            <div>
                                <img class="card__icon mt-5" src="{% static 'images/drinks.png' %}" alt="icon" />
                            </div>
                             <span>Food and Beverage — The Excitement Line</span>
                              <p class="info">
                                  To be excited is to not know what to expect, we all like the
                                  anticipation of what’s going to be serve.
                                  In our bar, there are variety of snacks and beverages options, even for
                                  non-coffee lovers; that’ll make you always excited for more.
                              </p>
                      </div>
                  </div>
              </div>
          </section>
          <!-- end about4 section -->
      </div>
    </main>
    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  </body>
</html>
{% endblock body %}

company/templates/information/album.html
{% extends 'base.html' %}
{% block body %}
<html>
    <head>
        <style>
           body{
            background-color: rgba(153,155,138,0.3);
           }
        </style>
    </head>
    <body>
        <!-- start Albom section -->
          <section class="albom">
            <div class="container">
                <div class="row">
                    {% for photo in photo_list %}
                        <div class="col-12 col-md-6 col-lg-3">
                            <img width="300" src="{{photo.image.url}}" alt="">
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    <!-- end Albom section -->
    </body>
</html>
{% endblock body %}

menu/templates/menu/albom.html
{% extends 'base.html' %}
{% block body %}
  <!-- start Albom section -->
  <section class="albom">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image/صور جانكن/نسخة من 1.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 3.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 4.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 4(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 7.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8(2).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 9.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 9(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 10.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 11.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 12.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 14.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 15.png" alt="">
            </div>  
        </div>
    </div>
</section>
<!-- end Albom section -->

{% endblock body %}

templates/base.html
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

<html {% if LANGUAGE_CODE == 'en' %}lang="en"{% else %}lang="ar" dir="rtl"{% endif %} >
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Janken</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- bootstrsp -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' media='screen' href='{% static 'style.css' %}'>


</head>
<body style="overflow-x: hidden;">

    <!-- start nav -->
    <header class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'company:home' %}">
                    <img src="{{company.logo.url}}" width="70" alt="">
                </a>
                <button style="border: none; outline: none;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'company:home' %}">{% translate "Home" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company:about' %}">{% translate "About" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'menu:menu_page' %}">{% translate "Menu" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company:contact' %}">{% translate "Contact" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'company:album' %}">{% translate "Album" %}</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="#">{{user.username}}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">{% translate "Logout" %}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'company:signup' %}">{% translate "Sign Up" %}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'login' %}">{% translate "Log In" %}</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <form action="{% url 'set_language' %}" method="post">
                                {% csrf_token %}
                                <input name="next" type="hidden" value="{{ redirect_to }}">
                                {% if LANGUAGE_CODE == 'ar' %}
                                    <input type="hidden" name="language" value="en">
                                    <input type="submit" class="submit" style="padding:3px 5px; margin-left:20px" value='English'>
                                {% else %}
                                    <input type="hidden" name="language" value="ar">
                                    <input type="submit" class="submit" style="padding:3px 5px; margin-left:20px" value='عربي'>
                                {% endif %}
                            </form>
                        </li>
                    </ul>
                </div>
                </div>
            </nav>
    </header>
    <!-- end nav -->
    {% block body %}{% endblock body %}
    <!-- start footer -->
    <div>
      <footer>
        <div class="row">
          <div class="col-2">

          </div>

          <div class="col-2">
            <h5>importent link</h5>
              <ul class="nav flex-column">
              <li><a class="text-white" href="{% url 'menu:menu_page' %}">{% translate "menu" %}</a></li>
              <li><a class="text-white" href="{% url 'login' %}">{% translate "log in" %}</a></li>
            </ul>
          </div>
          <div class="col-2">
            <h5>Contact us</h5>
            <ul class="nav flex-column">
              <li>{{company.phone}}</li>
              <li>{{company.email}}</li>
              <li>{{company.address}}</li>
            </ul>
          </div>

          <div class="col-4 offset-1">
            <img src="{% static 'image/logowh.png' %}" width="200" alt="">
            <p class="footer-p">{{company.sub_title}}</p>
          </div>
        </div>
        <div class="justify-content-between py-4 my-4 border-top">
          <p>&copy; 2023 UPM, Dept. Cyber Security & Forensic Computing. All rights reserved.</p>
        </div>
      </footer>
    </div>
    <!-- end footer -->

<!-- bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="{% static 'script.js' %}"></script>
</body>
</html>